### ISSUE TITLE
Confirm Stack

### ISSUE THREAD

**Issue by MattRueter** [chingu-voyages/v46-tier3-team-36#15]
Front end:

- [x] Next.js
- [ ] Vite
- [x] Tailwind
- [x] ShadCN [link to site](https://ui.shadcn.com/)
- [ ] Tailspark [link to site](https://tailspark.co/?component=Hero)
- [ ] MaterialUI

Back end:

- [x] Express
- [ ] Rails
 
Authentication:
- [ ] Passport

Hosting:

- [x] Supabase
- [ ] Firebase
- [ ] [Render](https://render.com/) 
- [ ] [fly](https://fly.io/)
- [ ] [aws](https://aws.amazon.com/free/?all-free-tier.sort-by=item.additionalFields.SortRank&all-free-tier.sort-order=asc&awsf.Free%20Tier%20Types=*all&awsf.Free%20Tier%20Categories=*all)
- [ ] Jamstack (github pages or vercel FE and ? BE API)

DB

- [ ] MySQL
- [x] PostgresSQL
- [ ] SQLite
- [ ] MongDB

ORM
- [x] Prisma

**Comment by MattRueter** [comment]
I suppose the best thing to do here would be in the meeting to discuss and then tick which we'll be using. 

I have made fullstack CRUD applications in MongoDB, React (VITE), Node/Express. I've been looking at the documentation for Next.js and have created a playground to learn it. So happy to use Next on the project. 
I'd vote for Express on the back-end as (I think most of us know that). I haven't learned SQL yet but I have all of you to help out :)

**Comment by n3ndor** [comment]
I'm really familiar with some Next.js functions (there are so many build in, it makes our job to look like a piece of cake).
Many thinks Next.js is only for front end, but Next.js is build for Server Side Rendering, so it has a build in backend too. 
(We could use as a fullstack if we want!) 
In bootcamp we learned python+jinja2+mySql and MERN both with full CRUD functionality, I'm good with all the technologies... Even if we pick something new to me, I will get fast into using it. At work I'm working on the frontend with next.js tailwind typescript, but I have a decent knowledge for fullstack.
